import { FileText, ChevronRight } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card.tsx";
import { Link } from "react-router-dom";

const SECTIONS = [
  {
    title: "Subscription Terms",
    content: `GOAT WALK Premium is a paid subscription service:

• Monthly subscription auto-renews unless cancelled at least 24 hours before the renewal date
• Pricing is displayed at the time of purchase and may change with advance notice
• Refunds are handled in accordance with Apple App Store or Google Play Store policies
• You can cancel your subscription at any time from Profile → My Subscription or through your app store account settings
• Cancelling stops future renewals; you retain access until the end of the current billing period
• The app owner account includes Premium access and does not require a paid subscription`,
  },
  {
    title: "AI Feature Usage",
    content: `GOAT WALK uses AI to generate personalized plans, coaching responses, and assessments:

• AI-generated plans (workout and nutrition) are personalized recommendations based on the data you provide
• AI assessments and body composition estimates are for informational and trend-tracking purposes only
• You may request modifications to your AI plan via the AI Coach — all plan changes require your explicit approval
• AI responses are generated by large language models and may occasionally contain errors or inconsistencies
• GOAT WALK reserves the right to update AI models and features to improve quality
• Excessive or abusive use of AI features may result in rate limiting or account review`,
  },
  {
    title: "User Responsibilities",
    content: `By using GOAT WALK you agree to:

• Provide accurate information about your health, fitness level, and goals
• Use the app for personal, non-commercial fitness purposes only
• Not attempt to reverse-engineer, copy, or redistribute any part of the app
• Not use the app to harm, harass, or deceive other users
• Keep your login credentials secure and not share your account
• Comply with all applicable laws and regulations in your jurisdiction
• Be at least 18 years old, or have parental consent if between 13–17 years old`,
  },
  {
    title: "Coaching Disclaimer",
    content: `GOAT WALK provides AI-powered fitness coaching tools:

• AI coaching is not a substitute for professional medical advice, diagnosis, or treatment
• Always consult a qualified healthcare provider before beginning any exercise or nutrition program, especially if you have pre-existing health conditions
• Progress photos and body composition estimates are for trend tracking only and are not medical assessments
• GOAT WALK coaches (where applicable) are fitness professionals, not licensed medical practitioners
• If you experience pain, discomfort, dizziness, or any adverse health effects, stop exercising and seek medical attention
• GOAT WALK is not responsible for any injury or health outcome resulting from following its recommendations`,
  },
  {
    title: "Limitation of Liability",
    content: `To the fullest extent permitted by applicable law:

• GOAT WALK is provided "as is" without warranties of any kind
• We are not liable for any indirect, incidental, special, or consequential damages
• Our total liability for any claim arising from use of the app is limited to the amount you paid in the 12 months preceding the claim
• We are not responsible for third-party services, payment processors, or AI model outputs
• These limitations apply even if GOAT WALK has been advised of the possibility of such damages`,
  },
  {
    title: "Account Termination",
    content: `GOAT WALK reserves the right to:

• Suspend or terminate accounts that violate these Terms
• Remove content that violates our policies
• Modify or discontinue features with reasonable notice

You may delete your account at any time from Profile → Delete Account. Account deletion is permanent and all data will be removed.`,
  },
  {
    title: "Changes to These Terms",
    content: `We may update these Terms of Service from time to time. When we do:

• We will update the "Last updated" date at the top of this page
• For significant changes, we will notify you via in-app notification or email
• Continued use of the app after changes constitutes acceptance of the updated terms

These terms were last updated: July 2025`,
  },
  {
    title: "Contact",
    content: `For questions about these Terms of Service:

legal@goatwalk.app

GOAT WALK · Last updated: July 2025`,
  },
];

export default function TermsPage() {
  return (
    <div className="max-w-2xl mx-auto px-4 pt-6 pb-10 space-y-6">
      {/* Header */}
      <div>
        <div className="flex items-center gap-2 mb-1">
          <FileText className="w-5 h-5 text-primary" />
          <p className="text-muted-foreground text-sm uppercase tracking-widest">Legal</p>
        </div>
        <h1 className="text-3xl font-black tracking-tight">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mt-1">Last updated: July 2025</p>
      </div>

      {/* Intro */}
      <Card className="border-primary/20 bg-primary/4">
        <CardContent className="p-4 text-sm text-muted-foreground leading-relaxed">
          By using GOAT WALK you agree to these Terms of Service. Please read them carefully. If you do not agree, do not use the app.
        </CardContent>
      </Card>

      {/* Sections */}
      <div className="space-y-4">
        {SECTIONS.map((section) => (
          <Card key={section.title} className="border-border bg-card">
            <CardContent className="p-5">
              <h2 className="font-bold text-base mb-3">{section.title}</h2>
              <p className="text-sm text-muted-foreground leading-relaxed whitespace-pre-line">{section.content}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Link to Privacy */}
      <div className="flex items-center justify-between pt-2 border-t border-border">
        <p className="text-xs text-muted-foreground">Also read our Privacy Policy</p>
        <Link to="/privacy-policy" className="flex items-center gap-1 text-xs text-primary font-medium cursor-pointer hover:underline">
          Privacy Policy <ChevronRight className="w-3.5 h-3.5" />
        </Link>
      </div>
    </div>
  );
}
