// Writes the iOS activity catalog — activities, browsing groups and the
// Activity Intelligence Framework's terms — from Sombrey's server-side
// activity model, so the app, the server and the AI Coach share one model.
// Run after changing convex/activityTaxonomy.ts or convex/activityFamilies.ts:
//   node --experimental-strip-types scripts/generate-activity-catalog.ts
// tests/activity checks the committed file is current.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { ACTIVITY_GROUPS, VENDOR_SPORT_TYPES, activityCatalog, isAmbiguousSportType } from "../convex/activityTaxonomy.ts";
import { ACTIVITY_FAMILIES, ACTIVITY_OVERRIDES, termsFor, type ActivityTerms } from "../convex/activityFamilies.ts";

export const CATALOG_SWIFT_PATH = fileURLToPath(
  new URL("../apps/ios/Sombrey/Training/Activity/ActivityCatalog.generated.swift", import.meta.url),
);

const quote = (s: string) => JSON.stringify(s);
const camel = (s: string) => s.replace(/_([a-z])/g, (_, c: string) => c.toUpperCase());

function renderTerms(t: ActivityTerms): string {
  const metrics = (list: string[]) => `[${list.map((m) => `.${camel(m)}`).join(", ")}]`;
  return `ActivityTerms(sessionNoun: ${quote(t.sessionNoun)}, verbPast: ${quote(t.verbPast)}, ` +
    `performanceTitle: ${quote(t.performanceTitle)}, movementTitle: ${quote(t.movementTitle)}, effortTitle: ${quote(t.effortTitle)}, ` +
    `primary: ${metrics(t.primary)}, secondary: ${metrics(t.secondary)}, ` +
    `notMeasured: ${t.notMeasured === undefined ? "nil" : quote(t.notMeasured)}, focus: ${quote(t.focus)}, ` +
    `recoveryNote: ${quote(t.recoveryNote)}, actionsLabel: ${quote(t.actionsLabel)}, ` +
    `paceUnit: .${t.paceUnit === "100m" ? "per100m" : "perKm"}, character: .${t.character})`;
}

export function renderCatalogSwift(): string {
  const catalog = activityCatalog();
  const groups = ACTIVITY_GROUPS.map((g) => `        ActivityGroup(id: ${quote(g.id)}, name: ${quote(g.name)}),`).join("\n");
  const activities = catalog
    .map((a) => `        SombreyActivity(key: ${quote(a.key)}, name: ${quote(a.name)}, category: ${quote(a.category)}, group: ${quote(a.group)}, vendorSportType: ${a.vendorSportType}, isAmbiguous: ${isAmbiguousSportType(a.vendorSportType)}),`)
    .join("\n");
  const vendorKeys = Object.keys(VENDOR_SPORT_TYPES)
    .map(Number)
    .sort((a, b) => a - b)
    .map((id) => `        ${id}: ${quote(VENDOR_SPORT_TYPES[id].key)},`)
    .join("\n");
  const families = Object.entries(ACTIVITY_FAMILIES)
    .map(([category, terms]) => `        ${quote(category)}: ${renderTerms(terms)},`)
    .join("\n");
  const byCategory = new Map(catalog.map((a) => [a.key, a.category]));
  const overrides = Object.keys(ACTIVITY_OVERRIDES)
    .filter((key) => byCategory.has(key))
    .sort()
    .map((key) => `        ${quote(key)}: ${renderTerms(termsFor(key, byCategory.get(key)!))},`)
    .join("\n");
  return `// GENERATED by scripts/generate-activity-catalog.ts from
// convex/activityTaxonomy.ts and convex/activityFamilies.ts — do not edit by hand.

extension ActivityCatalog {
    static let groups: [ActivityGroup] = [
${groups}
    ]

    static let all: [SombreyActivity] = [
${activities}
    ]

    /// Every band mode's Sombrey activity key (several modes share one).
    static let keyByVendorSportType: [Int: String] = [
${vendorKeys}
    ]

    /// The Activity Intelligence Framework: each category's terms…
    static let familyTerms: [String: ActivityTerms] = [
${families}
    ]

    /// …and, fully resolved, the activities that differ from their family.
    static let activityTerms: [String: ActivityTerms] = [
${overrides}
    ]
}
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(CATALOG_SWIFT_PATH, renderCatalogSwift());
  console.log(`wrote ${CATALOG_SWIFT_PATH}`);
}
