// Writes the iOS activity catalog from Sombrey's activity taxonomy, so the
// app and the server share one model. Run after changing
// convex/activityTaxonomy.ts:
//   node --experimental-strip-types scripts/generate-activity-catalog.ts
// tests/activity checks the committed file is current.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { ACTIVITY_GROUPS, VENDOR_SPORT_TYPES, activityCatalog } from "../convex/activityTaxonomy.ts";

export const CATALOG_SWIFT_PATH = fileURLToPath(
  new URL("../apps/ios/Sombrey/Training/Activity/ActivityCatalog.generated.swift", import.meta.url),
);

const quote = (s: string) => JSON.stringify(s);

export function renderCatalogSwift(): string {
  const groups = ACTIVITY_GROUPS.map((g) => `        ActivityGroup(id: ${quote(g.id)}, name: ${quote(g.name)}),`).join("\n");
  const activities = activityCatalog()
    .map((a) => `        SombreyActivity(key: ${quote(a.key)}, name: ${quote(a.name)}, category: ${quote(a.category)}, group: ${quote(a.group)}, vendorSportType: ${a.vendorSportType}),`)
    .join("\n");
  const vendorKeys = Object.keys(VENDOR_SPORT_TYPES)
    .map(Number)
    .sort((a, b) => a - b)
    .map((id) => `        ${id}: ${quote(VENDOR_SPORT_TYPES[id].key)},`)
    .join("\n");
  return `// GENERATED by scripts/generate-activity-catalog.ts from
// convex/activityTaxonomy.ts — do not edit by hand.

extension ActivityCatalog {
    static let groups: [ActivityGroup] = [
${groups}
    ]

    static let all: [SombreyActivity] = [
${activities}
    ]

    /// Every band mode's Sombrey activity key (several modes share one).
    static let keyByVendorSportType: [Int: String] = [
${vendorKeys}
    ]
}
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(CATALOG_SWIFT_PATH, renderCatalogSwift());
  console.log(`wrote ${CATALOG_SWIFT_PATH}`);
}
